name: First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: List and Read File
        run: |
          echo "Welcome to github actions"
          ls -ltra
          cat README.md

      - name: Install Cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "This is GitHub Action demo" >> dragon.txt

      - name: Display Generated ASCII Art
        run: cat dragon.txt

      # - name: List of files
      #   run: ls

      # - name:
      #   run: cat README.md