name: Multi-Jobs

on:
  push

jobs:
  test_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsey Program
        run: |
          sudo apt-get update 
          sudo apt-get install -y cowsay
      - name: Execute Cowsey Program
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      
      - name: Sleep 30 s
        run: sleep 30


  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 30 s
        run: sleep 30

      - name: Test Exist File
        run: grep -i "dragon" dragon.txt

  test_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 30 s
        run: cat dragon.txt
      
      - name: Test Exist File
        run: ls -ltra