name: First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: welcome message
        run: echo "Welcome to github actions"

      - name: List of files
        run: ls

      - name:
        run: cat README.md