name: First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: List and Read File
        run: |
          echo "Welcome to github actions"
          la -ltra
          cat cat README.md

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "This is github action demo" >> dragon.txt

      # - name: List of files
      #   run: ls

      # - name:
      #   run: cat README.md